name: build
on:
  workflow_dispatch:
  
permissions:
  contents: write
  
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Checkout submodules
        run: git submodule update --init --recursive --remote

      - name: Download latest lists
        run: |
          curl -L -o ./V2rayNG/app/libs/libv2ray.aar https://github.com/Tony0812-dev/AndroidLibV2rayLite/releases/download/main/libv2ray.aar
          curl -L -o ./V2rayNG/app/libs/libv2ray-sources.jar https://github.com/Tony0812-dev/AndroidLibV2rayLite/releases/download/main/libv2ray-sources.jar

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 11

      - name: Grant execute permission for gradlew
        run: cd V2rayNG && chmod +x gradlew

      - name: Build with Gradle
        run: cd V2rayNG && ./gradlew assembleDebug

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: main
          release_name: rel
          files: ./V2rayNG/app/build/outputs/apk/prod/debug/*.apk
          prerelease: false
          generate_release_notes: true
